### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by lorengordon** [claranet/terraform-aws-lambda#19]
Thanks for this awesome module! I tend to flip between platforms a lot, developing on Windows for Linux-based systems. If I can get this working on Windows, would you be open to a pull request? Looks like some folks have been recommending/doing things that definitely wouldn't work, like using python2/python3 executables, relying on the shebang, etc... So, if you want to keep that, then I won't bother and will just keep using the Windows subsystem for Linux.

**Comment by lorengordon** [comment]
Current error on Windows (there will probably be many, as I peel back the onion):

```
data.external.archive: failed to execute .... hash.py: %1 is not a valid Win32 application.
```

hash.py executes just fine on Windows when I run it manually, whether I call it as `python hash.py` or just `hash.py`, so likely a difference in the environment when it is executed through Go.

**Comment by raymondbutcher** [comment]
Done in #20 + #31
