### ISSUE TITLE
module_relpath seems to be broken under version 0.12.0

### ISSUE THREAD

**Issue by wutianchen** [claranet/terraform-aws-lambda#48]
I am fitting the module to hcl2.0 namely terraform version 0.12.0, but has difficulty to understand the path variable in archive.tf

```
locals {
  module_relpath = "${substr(path.module, length(path.cwd) + 1, -1)}"
}
```

what does it really mean ? shouldn't it be ?

`module_relpath  = "${path.module}"`

thanks

**Comment by raymondbutcher** [comment]
Hi @wutianchen. I think I've fixed this in 3b36ece7f4b0b878e846227d63d320d78a37e0b4 but of course there are a bunch of other issues remaining :)

I'll see what else I can fix in a backwards compatible way, although some of the comments in #47 sound like we may have to have separate branches for 0.11.x and 0.12.x. We'll see.
