### ISSUE TITLE
No release was created for the latest commit in master branch

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [claranet/terraform-aws-lambda#69]
Hi! Latest commit to master branch is this: https://github.com/claranet/terraform-aws-lambda/commit/f9ff6ee0788e187327c182f691041fbc9527e080

However, latest release tag is this: https://github.com/claranet/terraform-aws-lambda/commits/v1.1.0 and it's pointing to this commit: https://github.com/claranet/terraform-aws-lambda/commit/ace2bc9193e79be6b0548db4ab78b7040b864237 which is one commit behind f9ff6ee0788e187327c182f691041fbc9527e080 (master).

Could you create a new release tag for the latest commit in master branch? Thanks!

**Comment by raymondbutcher** [comment]
Hi. Sorry for the delay, it's in the v1.2.0 now.
